image: golang:1.19

services:
  - docker:dind

variables:
  TAG_LATEST: $CI_

stages:
  - build
  - test
  - dev-deploy

build:
  stage: build
  image: docker:latest
  script:
    - go mod download
    - go mod verify
  artifacts:
    paths:
      - /src/app
  only:
    - develop

test:
  stage: test
  image: golang:1.19.2-alpine3.16
  script:
    - go test -v ./...
  dependencies:
    - build
  only:
    - develop

deploy:
  stage: dev-deploy
  image: golang:1.19.2-alpine3.16
  script:
    - go build -o /src/app
    - ./src/app
  dependencies:
    - test
  only:
    - main